# Generated by Django 4.1.2 on 2022-10-11 10:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_short_name', models.CharField(max_length=50)),
                ('legal_structure', models.CharField(choices=[('Company', 'Company'), ('LLP', 'LLP'), ('Individual', 'Individual')], max_length=15)),
                ('contact_person_first_name', models.CharField(max_length=255)),
                ('contact_person_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_person_last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10)),
                ('primary_cost_center', models.CharField(choices=[('Distribution', 'Distribution'), ('Logistics', 'Logistics')], max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankingDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='add_new_client.clientdetail')),
                ('account_code', models.CharField(max_length=20)),
                ('account_no', models.CharField(max_length=17)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_city', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('bank_document', models.FileField(upload_to='bankDocument/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunicationDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Invalid pin code')])),
                ('zone', models.CharField(choices=[('Central Zone', 'Central Zone'), ('East Zone', 'East Zone'), ('East Zone1', 'East Zone1'), ('North East Zone', 'North East Zone'), ('North Zone', 'North Zone'), ('South Zone', 'South Zone'), ('Union Territory', 'Union Territory'), ('West Zone', 'West Zone')], max_length=50)),
                ('state', models.CharField(choices=[('Bihar', 'Bihar'), ('Jharkhand', 'Jharkhand'), ('Odisha', 'Odisha'), ('Test State', 'Test State'), ('West Bengal', 'West Bengal')], max_length=50)),
                ('city', models.CharField(choices=[('none', 'none')], max_length=50)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='add_new_client.clientdetail')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('alternate_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentAndProof',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='add_new_client.clientdetail')),
                ('pan_number', models.CharField(max_length=10)),
                ('adhar_number', models.CharField(max_length=12)),
                ('gst_reg_type', models.CharField(choices=[('Registered', 'Registered'), ('Unregistered', 'Unregistered')], max_length=15)),
                ('gst_number', models.CharField(max_length=15)),
                ('pan_document', models.FileField(upload_to='panDocument/')),
                ('adhar_document', models.FileField(upload_to='adharDocument/')),
                ('gst_document', models.FileField(upload_to='gstDocument/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='add_new_client.clientdetail')),
                ('related_party', models.BooleanField(blank=True, null=True)),
                ('black_listed', models.BooleanField(blank=True, null=True)),
                ('same_as_billing_location', models.BooleanField(blank=True, null=True)),
                ('document_currency', models.CharField(max_length=255)),
                ('credit_period', models.CharField(max_length=255)),
                ('credit_amount', models.FloatField()),
                ('payment_terms_and_condition', models.TextField()),
                ('exempt_from_tax', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShippingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Invalid pin code')])),
                ('zone', models.CharField(choices=[('Central Zone', 'Central Zone'), ('East Zone', 'East Zone'), ('East Zone1', 'East Zone1'), ('North East Zone', 'North East Zone'), ('North Zone', 'North Zone'), ('South Zone', 'South Zone'), ('Union Territory', 'Union Territory'), ('West Zone', 'West Zone')], max_length=50)),
                ('state', models.CharField(choices=[('Bihar', 'Bihar'), ('Jharkhand', 'Jharkhand'), ('Odisha', 'Odisha'), ('Test State', 'Test State'), ('West Bengal', 'West Bengal')], max_length=50)),
                ('city', models.CharField(choices=[('none', 'none')], max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_new_client.clientdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Invalid pin code')])),
                ('zone', models.CharField(choices=[('Central Zone', 'Central Zone'), ('East Zone', 'East Zone'), ('East Zone1', 'East Zone1'), ('North East Zone', 'North East Zone'), ('North Zone', 'North Zone'), ('South Zone', 'South Zone'), ('Union Territory', 'Union Territory'), ('West Zone', 'West Zone')], max_length=50)),
                ('state', models.CharField(choices=[('Bihar', 'Bihar'), ('Jharkhand', 'Jharkhand'), ('Odisha', 'Odisha'), ('Test State', 'Test State'), ('West Bengal', 'West Bengal')], max_length=50)),
                ('city', models.CharField(choices=[('none', 'none')], max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_new_client.clientdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
